### PR TITLE
Updated instructions for switching back from Android

### PR DESCRIPTION
**Pull request by roihershberg**
Instructions for switching from Android to postmarketOS without PC.

### CODE REVIEW

**Comment by kcxt** [comment]
Looks good, the app requires that magisk module right? Unless your ROM ships bootctl? It might be worth making that slightly clearer.

**Comment by roihershberg** [comment]
The app doesn't specify that magisk module because I created it. I think the app is supposed to work with classic su in android where all the binaries of the system are exposed to you. The thing with magisk is that it is systemless rooting so no access to binaries of the system partition (as far as I understood it).
I booted to TWRP to check if I have that "bootctl" binary and I did. I have it in the directory: "/sbin" so it is in the ROM but with MagiskSU I think you can't access it.

So as far as I know, the ROM ships bootctl but if you're using MagiskSU you can't access it so you'll need to install the module that I created that mounts that binary at boot to the "/system/xbin/" folder. Otherwise the app is crashing at start because it's trying to execute a command that do not exist. (The developers didn't implement a logic where they check if the command exists)

Tell me if you think that I should add some of that information to the instructions. (I prefer not to because I don't really know what is going there)

**Comment by roihershberg** [comment]
I added some info

**Comment by roihershberg** [comment]
I removed the instructions for Magisk because I moved them to Switch My Slot README.
It's now as simple as pointing to the app.

**Comment by kcxt** [comment]
Ok this looks great, could you squash the commits back into one? Then good to merge.

**Comment by roihershberg** [comment]
Yes, I squashed them.

**Pull request merged**
